name: Deploy

on:
    push:
        branches: [ "stage" ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   name: Use Node.js 18.x
                uses: actions/setup-node@v3
                with:
                    node-version: 18.x

            -   name: Build
                run: |
                    npm install
                    npm run build

            -   name: Deploy
                uses: garygrossgarten/github-action-scp@release
                with:
                    local: dist
                    remote: /home/github/agylam/back
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.SSH_USER }}
                    password: ${{ secrets.SSH_PASSWORD }}