name: Push

on:
  push:
    branches: [ "cicd-test" ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DK_USERNAME }}
          password: ${{ secrets.DK_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: docker/Dockerfile
          context: .
          push: true
          tags: agylam/back:${{ github.ref_name }}